sudo: required

language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: api-testing-training-01
    token: "${SONAR_TOKEN}"

script:
  - ./gradlew check
  - sonar-scanner
  - ./gradlew executeBDDTests -PcucumberOptions="--tags @acceptance" -PcucumberThreadCount="2"

notifications:
  email: true

before_install:
  - openssl aes-256-cbc -K $encrypted_c5fd3201494e_key -iv $encrypted_c5fd3201494e_iv
    -in config.json.enc -out config.json -d
